linters:
  enable-all: true
  disable:
    - funlen
    - godot
    - exhaustivestruct
    - gocognit

linters-settings:
  wsl:
    allow-cuddle-declarations: true
  gci:
    local-prefixes: github.com/gordonbondon/terraform-provider-maxminddb

issues:
  exclude-rules:
    - linters:
        - wsl
        - errcheck
        - dogsled
        - funlen
        - scopelint
        - golint
        - unparam
        - gochecknoglobals
        - paralleltest
        - testpackage
        - stylecheck
      path: tests|_test\.go
    - linters:
        - forbidigo
        - goerr113
        - gomnd
      path: main.go
    - linters:
        - gochecknoinits
      path: provider.go
