name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3.4.0
        with:
          go-version: '1.15'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.3
        with:
          submodules: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.35

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: |
          go mod download

      - name: lint provider
        run: |
          make tools

          terrafmt diff --check --quiet --fmtcompat ./internal/provider

          tfproviderlint -AT004=false ./...

          tfproviderdocs check -provider-name=terraform-provider-maxminddb .

  # run acceptance tests in a matrix with Terraform core versions
  test:
    name: Matrix Test
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - '0.12.30'
          - '0.13.6'
          - '0.14.4'
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3.4.0
        with:
          go-version: '1.15'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.3
        with:
          submodules: true

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: |
          go mod download

      - name: TF acceptance tests
        timeout-minutes: 10
        env:
          TF_ACC: "1"
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}

        run: |
          go test -v -cover ./internal/provider/
